services:
  postgres:
    image: postgres:17
    container_name: menv-postgres
    environment:
      POSTGRES_DB: menv
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pg@menv!
    ports:
      - "5432:5432"
